### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by amshkv** [Hexlet/runit#31]
<img width="177" alt="image" src="https://user-images.githubusercontent.com/23584933/199647435-6ba37dbb-5be1-4566-9e26-ad2c9bde9dcb.png">

**Comment by acidmaksim** [comment]
![Image](https://user-images.githubusercontent.com/77053797/199658598-e5883e08-ba87-4637-89e9-b59f0d9a496c.svg)

**Comment by dzencot** [comment]
Уже добавил)
