### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/runit#38]
Make footer as in [Hexlet](http://hexlet.io/), all the links that are in the footer in Hexlet: offer, processing AP, contacts, etc.

**Comment by rabbanirizwan** [comment]
@acidmaksim  kindly assign me this task

**Comment by Asya-Kamaeva** [comment]
@rabbanirizwan why? I'm already on it..

**Comment by Asya-Kamaeva** [comment]
@acidmaksim есть два вопроса:
1) ссылки на https://ru.hexlet.io/my все разношерстные https://take.ms/gaoem , я их просто копирую оттуда? получается на runit все ссылки будут абсолютными, верно?
2) что должно происходить при переключении языка https://take.ms/Pj34f ? я так понимаю у runit сейчас одна версия - русская, делаю пока просто кнопки, без какого либо функционала?

**Comment by acidmaksim** [comment]
@dzencot подскажи, пожалуйста

**Comment by dzencot** [comment]
1. Да, просто скопируй
2. Пока без функционала, да
