### ISSUE TITLE
Replace tag on landing

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/runit#40]
H3 (

[https://yadi.sk/d/Wnl0F9uDKSMUPQ](https://yadi.sk/d/Wnl0F9uDKSMUPQ)

) replace with any other tag not h1-6

H4 (

[https://yadi.sk/i/t5mavEAxiMd-ZA](https://yadi.sk/i/t5mavEAxiMd-ZA)

) replace with any other tag not h1-6

**Comment by Funkicide** [comment]
Беру)
