### ISSUE TITLE
Logging in and registration doesn't work

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/runit#55]

**Comment by LarendsD** [comment]
Работаю над этой задачей, вопрос такой, развернул этот проект у себя на хероку https://runit-hexlet.herokuapp.com/ , сбрасывал бд, делал миграции не раз, всё работает, изменения последние все есть, соответсвенно получается не могу отследить вообще никак по логам эту ошибку, так как ошибки у меня этой нет

**Comment by dzencot** [comment]
@acidmaksim а что это за ошибка? Это когда миграции не обновляли? Тоже не могу воспроизвести. Возможно это была разовая проблема

**Comment by acidmaksim** [comment]
Попробуй сейчас зарегистрироваться, у тебя 500 ошибка будет. 
Нужно как то ее отловить и понять почему не работает

**Comment by dzencot** [comment]
поправил
