### ISSUE TITLE
Make redirections

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/runit#7]
Make redirections http://runit.hexlet.ru/ to [https://runit.hexlet.ru](http://runit.hexlet.ru/)

**Comment by acidmaksim** [comment]
http://hexlet-editor.herokuapp.com/ отсюда тоже

**Comment by Blinina** [comment]
К сожалению, вынуждена отказаться от задачи.
Спасибо.

**Comment by LarendsD** [comment]
@acidmaksim привет! Я так понимаю тут нужно просто перенести проект с протокола HTTP на протокол HTTPS, так?

**Comment by acidmaksim** [comment]
Чтобы с HTTP редиректил на HTTPS

**Comment by LarendsD** [comment]
Понял, беру в работу
