### ISSUE TITLE
We need to add a snippet design for insertion on websites and presentations. The snippet consists of a field with the source code, a field with the return value and stdout output.

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/runit#9]
We need to add a snippet design for insertion on websites and presentations. Можно реализовать это через Iframe
Example on [codesandbox](https://codesandbox.io/s/sweet-bell-is0g5o): 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/77053797/196444380-af1a1665-c59d-4dd4-8a75-95ee7e1c67d7.png">

**Comment by Takaiva** [comment]
Taking this one!
